services:
  - type: web
    name: surprise-ai-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PORT
        value: 8000  # За замовчуванням, Render перезапише це
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://surprise-ai-bot.onrender.com
